[build]
  command = "npm run build && npm run build:functions"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@firebase/firestore"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure Netlify handles SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200